.\" BSD 2-Clause License
.\"
.\" Copyright (c) 2018, Carlos Donizete Froes [a.k.a coringao]
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions are met:
.\"
.\" * Redistributions of source code must retain the above copyright notice, this
.\"   list of conditions and the following disclaimer.
.\"
.\" * Redistributions in binary form must reproduce the above copyright notice,
.\"   this list of conditions and the following disclaimer in the documentation
.\"   and/or other materials provided with the distribution.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
.\" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
.\" DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
.\" SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
.\" CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
.\" OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
.\" OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
.TH cavestory-nx "6" "July 2018" "Cave Story NX"
.SH NAME
cavestory-nx \- is a nostalgic side action adventure game to jump and shoot.
.PP
.SH DESCRIPTION
.br
You control a little amnesiac who runs around helping out these rabbit-ish creatures called Mimigas
while trying to find your way out of the giant cave inside the floating island which makes up the game's setting.
.PP
You can expand your health meter by collecting Life Capsules, while you can get stronger by collecting energy
to boost your firearms output.
.PP
Each weapon can be built up to the maximum level (3) fairly quickly, but taking damage will drain energy
from its experience meter, sometimes causing it to level down.
.PP
Given how quickly they power up this only tends to be an issue during boss fights, and even then there's
usually plenty of opportunities for collecting more weapon energy.
.br
.PP
.SH CONTROLS
.br
.B	KEY							ACTION
.br
===							======
.br
Left-arrow and Right-arrow		Move left and right
.br
Up-arrow						Look up
.br
Down-arrow					Search (or look down in midair)
.br
Z key						Jump
.br
X key						Fire weapon
.br
A key (back) and S key (forward)	Change weapon
.br
Q key						Item Screen
.br
W key						Display map (requires item)
.PP
-------------------------------------------------------------------
.br
.B	KEY							CONVERSATION
.br
===							============
.br
Left-arrow and Right-arrow		Yes/No selection
.br
X key or Z key					Continue conversation
.PP
-------------------------------------------------------------------
.br
.B	KEY							ITEM SCREEN
.br
===							===========
.br
Arrow keys					Selection
.br
Z key						Examine/Use
.br
X key						Leave Screen
.br
.PP
You can quit or reset the game by pressing ESC.
.br
.SH AUTHOR
.B Tools and data used:
.br
NXEngine by Caitlin Shaw. Updated/refactored by NXEngine-evo is a reproduction of the Cave Story engine.
.br
Author of game data from Studio Pixel [Daisuke Amaya also known by his art name 'Pixel'].
.PP
This manual page was written by Carlos Donizete Froes [a.k.a coringao], for the Debian project (but may be used by others).
