.\" BSD 2-Clause License
.\"
.\" Copyright (c) 2018, Carlos Donizete Froes [a.k.a coringao]
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions are met:
.\"
.\" * Redistributions of source code must retain the above copyright notice, this
.\"   list of conditions and the following disclaimer.
.\"
.\" * Redistributions in binary form must reproduce the above copyright notice,
.\"   this list of conditions and the following disclaimer in the documentation
.\"   and/or other materials provided with the distribution.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
.\" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
.\" DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
.\" SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
.\" CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
.\" OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
.\" OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
.TH cavestory-nx "6" "July 2018" "Cave Story NX"
.SH NAME
cavestory-nx \- is a nostalgic side action adventure game to jump and shoot.
.PP
.SH DESCRIPTION
.br
Cave Story is a side-scrolling platform game that can be played with either
the keyboard or a gamepad. Players will solve puzzles and fight enemies on each
map while trying to collect weapons and items to help him along the way.
.PP
Includes some RPG elements with more than three dozen different items
that can be found and stored in the player's inventory for later use.
.PP
Players won't get tired of fighting the same monsters over and over again
simply because there are so many different monsters in game and there always
seems to be something new to tackle where each representing a unique set of
challenges that the player must overcome to defeat.
.br
.PP
.SH CONTROLS
.br
.B	KEY							ACTION
.br
===							======
.br
Left-arrow and Right-arrow		Move left and right
.br
Up-arrow						Look up
.br
Down-arrow					Search (or look down in midair)
.br
Z key						Jump
.br
X key						Fire weapon
.br
A key (back) and S key (forward)	Change weapon
.br
Q key						Item Screen
.br
W key						Display map (requires item)
.PP
-------------------------------------------------------------------
.br
.B	KEY							CONVERSATION
.br
===							============
.br
Left-arrow and Right-arrow		Yes/No selection
.br
X key or Z key					Continue conversation
.PP
-------------------------------------------------------------------
.br
.B	KEY							ITEM SCREEN
.br
===							===========
.br
Arrow keys					Selection
.br
Z key						Examine/Use
.br
X key						Leave Screen
.br
.PP
You can quit or reset the game by pressing ESC.
.br
.SH AUTHORS
.B Tools and data used:
.br
NXEngine by Caitlin Shaw. Updated/refactored by NXEngine-evo is a reproduction of the Cave Story engine.
.br
Source of the game developed by Daisuke Amaya known by the stage name of "Pixel".
.PP
This manual page was written by Carlos Donizete Froes [a.k.a coringao], for the Debian project (but may be used by others).
